## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('two-clocks-no-update', ['clock', 'point-to-point', 'internet', 'applications','network'])
    obj.source = 'two-clocks-no-update.cc'

    obj = bld.create_ns3_program('two-clocks-update', ['clock', 'point-to-point', 'internet', 'applications','network'])
    obj.source = 'two-clocks-update.cc'
