## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('two-clocks-simple', ['clock', 'point-to-point', 'internet', 'applications','network'])
    obj.source = 'two-clocks-simple.cc'
