# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('clock', ['core'])
    module.source = [
        'model/clock-model.cc',
        'model/local-clock.cc',
        'model/localtime-simulator-impl.cc',
        'model/perfect-clock-model-impl.cc',
        'helper/clock-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('clock',)
    module_test.source = [
        'test/clock-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'clock'
    headers.source = [
        'model/clock-model.h',
        'model/local-clock.h',
        'model/localtime-simulator-impl.h',
        'model/perfect-clock-model-impl.h',
        'helper/clock-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

   

    bld.ns3_python_bindings()

